import Head from "next/head";
// import { Header } from "./_components/Header";
import Content from "./_components/Content";
import Footer from "./_components/Footer";
import Navbar from "./_components/Navbar";

const Home = () => {
  return (
    <>
      <Head>
        <title>Note-Taker</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <Header /> */}
        <Navbar />
        <Content />
        <Footer />
      </main>
    </>
  );
};

export default Home;
